### ISSUE TITLE
react+ vite+ ts  子应用 接入 qiankun

### ISSUE THREAD

**Issue by wmx-us** [skywalk94/qiankun-demo#1]
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
// import { unmountComponentAtNode } from "react-dom";
import { renderWithQiankun, qiankunWindow } from "vite-plugin-qiankun/dist/helper";

import "./index.css";
interface IContainer {
  container: HTMLElement;
}

const render = (container?: HTMLElement) => {
  const appDom = container ? container : (document.getElementById("micro-container") as HTMLElement);
  ReactDOM.createRoot(appDom).render(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
  );
};

const initQianKun = () => {
  renderWithQiankun({
    // 当前应用在主应用中的生命周期
    // 文档 https://qiankun.umijs.org/zh/guide/getting-started#

    mount(props: any) {
      render(props.container);

      props.onGlobalStateChange((res: any) => {
        console.log("res :>> ", res);
      });
    },
    bootstrap() {},
    unmount() [{},](url)

-   } as any);
@
};

qiankunWindow.__POWERED_BY_QIANKUN__ ? initQianKun() : render();``

还是会提示 报红 但是项目是接入OK的 
<img width="510" alt="企业微信截图_16866467905417" src="https://github.com/skywalk94/qiankun-demo/assets/68103050/7ee63cdf-40b3-4683-9652-1f8db222c881">

**Comment by skywalk94** [comment]
你好，可以看看这篇文章，希望能帮到你 https://iapex.blog.csdn.net/article/details/127430028
